import { LayoutLikeObject } from "./types";

export const countryCodes = ["nl", "pl", "ca", "ch", "cn", "co", "cu"];
export const countriesPath = "/countries/";
export const mainClassNames: LayoutLikeObject = { list: "main--withList", tile: "main--withTiles" };

export const countryList = {
    AF: "Afghanistan",
    AL: "Albania",
    DZ: "Algeria",
    AS: "American Samoa",
    AD: "Andorra",
    AO: "Angola",
    AI: "Anguilla",
    AQ: "Antarctica",
    AG: "Antigua and Barbuda",
    AR: "Argentina",
    AM: "Armenia",
    AW: "Aruba",
    AU: "Australia",
    AT: "Austria",
    AZ: "Azerbaijan",
    BS: "Bahamas (the)",
    BH: "Bahrain",
    BD: "Bangladesh",
    BB: "Barbados",
    BY: "Belarus",
    BE: "Belgium",
    BZ: "Belize",
    BJ: "Benin",
    BM: "Bermuda",
    BT: "Bhutan",
    BO: "Bolivia (Plurinational State of)",
    BQ: "Bonaire, Sint Eustatius and Saba",
    BA: "Bosnia and Herzegovina",
    BW: "Botswana",
    BV: "Bouvet Island",
    BR: "Brazil",
    IO: "British Indian Ocean Territory (the)",
    BN: "Brunei Darussalam",
    BG: "Bulgaria",
    BF: "Burkina Faso",
    BI: "Burundi",
    CV: "Cabo Verde",
    KH: "Cambodia",
    CM: "Cameroon",
    CA: "Canada",
    KY: "Cayman Islands (the)",
    CF: "Central African Republic (the)",
    TD: "Chad",
    CL: "Chile",
    CN: "China",
    CX: "Christmas Island",
    CC: "Cocos (Keeling) Islands (the)",
    CO: "Colombia",
    KM: "Comoros (the)",
    CD: "Congo (the Democratic Republic of the)",
    CG: "Congo (the)",
    CK: "Cook Islands (the)",
    CR: "Costa Rica",
    HR: "Croatia",
    CU: "Cuba",
    CW: "Curaçao",
    CY: "Cyprus",
    CZ: "Czechia",
    CI: "Côte d'Ivoire",
    DK: "Denmark",
    DJ: "Djibouti",
    DM: "Dominica",
    DO: "Dominican Republic (the)",
    EC: "Ecuador",
    EG: "Egypt",
    SV: "El Salvador",
    GQ: "Equatorial Guinea",
    ER: "Eritrea",
    EE: "Estonia",
    SZ: "Eswatini",
    ET: "Ethiopia",
    FK: "Falkland Islands (the) [Malvinas]",
    FO: "Faroe Islands (the)",
    FJ: "Fiji",
    FI: "Finland",
    FR: "France",
    GF: "French Guiana",
    PF: "French Polynesia",
    TF: "French Southern Territories (the)",
    GA: "Gabon",
    GM: "Gambia (the)",
    GE: "Georgia",
    DE: "Germany",
    GH: "Ghana",
    GI: "Gibraltar",
    GR: "Greece",
    GL: "Greenland",
    GD: "Grenada",
    GP: "Guadeloupe",
    GU: "Guam",
    GT: "Guatemala",
    GG: "Guernsey",
    GN: "Guinea",
    GW: "Guinea-Bissau",
    GY: "Guyana",
    HT: "Haiti",
    HM: "Heard Island and McDonald Islands",
    VA: "Holy See (the)",
    HN: "Honduras",
    HK: "Hong Kong",
    HU: "Hungary",
    IS: "Iceland",
    IN: "India",
    ID: "Indonesia",
    IR: "Iran (Islamic Republic of)",
    IQ: "Iraq",
    IE: "Ireland",
    IM: "Isle of Man",
    IL: "Israel",
    IT: "Italy",
    JM: "Jamaica",
    JP: "Japan",
    JE: "Jersey",
    JO: "Jordan",
    KZ: "Kazakhstan",
    KE: "Kenya",
    KI: "Kiribati",
    KP: "Korea (the Democratic People's Republic of)",
    KR: "Korea (the Republic of)",
    KW: "Kuwait",
    KG: "Kyrgyzstan",
    LA: "Lao People's Democratic Republic (the)",
    LV: "Latvia",
    LB: "Lebanon",
    LS: "Lesotho",
    LR: "Liberia",
    LY: "Libya",
    LI: "Liechtenstein",
    LT: "Lithuania",
    LU: "Luxembourg",
    MO: "Macao",
    MG: "Madagascar",
    MW: "Malawi",
    MY: "Malaysia",
    MV: "Maldives",
    ML: "Mali",
    MT: "Malta",
    MH: "Marshall Islands (the)",
    MQ: "Martinique",
    MR: "Mauritania",
    MU: "Mauritius",
    YT: "Mayotte",
    MX: "Mexico",
    FM: "Micronesia (Federated States of)",
    MD: "Moldova (the Republic of)",
    MC: "Monaco",
    MN: "Mongolia",
    ME: "Montenegro",
    MS: "Montserrat",
    MA: "Morocco",
    MZ: "Mozambique",
    MM: "Myanmar",
    NA: "Namibia",
    NR: "Nauru",
    NP: "Nepal",
    NL: "Netherlands (the)",
    NC: "New Caledonia",
    NZ: "New Zealand",
    NI: "Nicaragua",
    NE: "Niger (the)",
    NG: "Nigeria",
    NU: "Niue",
    NF: "Norfolk Island",
    MP: "Northern Mariana Islands (the)",
    NO: "Norway",
    OM: "Oman",
    PK: "Pakistan",
    PW: "Palau",
    PS: "Palestine, State of",
    PA: "Panama",
    PG: "Papua New Guinea",
    PY: "Paraguay",
    PE: "Peru",
    PH: "Philippines (the)",
    PN: "Pitcairn",
    PL: "Poland",
    PT: "Portugal",
    PR: "Puerto Rico",
    QA: "Qatar",
    MK: "Republic of North Macedonia",
    RO: "Romania",
    RU: "Russian Federation (the)",
    RW: "Rwanda",
    RE: "Réunion",
    BL: "Saint Barthélemy",
    SH: "Saint Helena, Ascension and Tristan da Cunha",
    KN: "Saint Kitts and Nevis",
    LC: "Saint Lucia",
    MF: "Saint Martin (French part)",
    PM: "Saint Pierre and Miquelon",
    VC: "Saint Vincent and the Grenadines",
    WS: "Samoa",
    SM: "San Marino",
    ST: "Sao Tome and Principe",
    SA: "Saudi Arabia",
    SN: "Senegal",
    RS: "Serbia",
    SC: "Seychelles",
    SL: "Sierra Leone",
    SG: "Singapore",
    SX: "Sint Maarten (Dutch part)",
    SK: "Slovakia",
    SI: "Slovenia",
    SB: "Solomon Islands",
    SO: "Somalia",
    ZA: "South Africa",
    GS: "South Georgia and the South Sandwich Islands",
    SS: "South Sudan",
    ES: "Spain",
    LK: "Sri Lanka",
    SD: "Sudan (the)",
    SR: "Suriname",
    SJ: "Svalbard and Jan Mayen",
    SE: "Sweden",
    CH: "Switzerland",
    SY: "Syrian Arab Republic",
    TW: "Taiwan",
    TJ: "Tajikistan",
    TZ: "Tanzania, United Republic of",
    TH: "Thailand",
    TL: "Timor-Leste",
    TG: "Togo",
    TK: "Tokelau",
    TO: "Tonga",
    TT: "Trinidad and Tobago",
    TN: "Tunisia",
    TR: "Turkey",
    TM: "Turkmenistan",
    TC: "Turks and Caicos Islands (the)",
    TV: "Tuvalu",
    UG: "Uganda",
    UA: "Ukraine",
    AE: "United Arab Emirates (the)",
    GB: "United Kingdom of Great Britain and Northern Ireland (the)",
    UM: "United States Minor Outlying Islands (the)",
    US: "United States of America (the)",
    UY: "Uruguay",
    UZ: "Uzbekistan",
    VU: "Vanuatu",
    VE: "Venezuela (Bolivarian Republic of)",
    VN: "Viet Nam",
    VG: "Virgin Islands (British)",
    VI: "Virgin Islands (U.S.)",
    WF: "Wallis and Futuna",
    EH: "Western Sahara",
    YE: "Yemen",
    ZM: "Zambia",
    ZW: "Zimbabwe",
    AX: "Åland Islands",
};
export const sourceNamePL = "fake source name PL";
export const articlesPL = [
    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "Onet",
        title: "Przełom w sprawie wycieczek młodzieży z Izraela. Jest umowa - Onet",
        description: null,
        url: "https://news.google.com/rss/articles/CBMicmh0dHBzOi8vd3d3Lm9uZXQucGwvaW5mb3JtYWNqZS9vbmV0d2lhZG9tb3NjaS9qZXN0LXVtb3dhLXotaXpyYWVsZW0tdy1zcHJhd2llLXd5Y2llY3play1tbG9kemllenkvczVta2dxaCw3OWNmYzI3ONIBAA?oc=5",
        urlToImage:
            "https://www.rtlboulevard.nl/sites/default/files/content/images/2023/03/22/Schermafbeelding%202023-03-22%20om%2021.57.37.jpg?itok=K3Z_MbbH&offsetX=0&offsetY=0&cropWidth=1681&cropHeight=946&width=2048&height=1152&impolicy=dynamic",
        publishedAt: "2023-03-23T08:17:54Z",
        content:
            "Over ruim een maand, vanaf 24 april, kunnen er weer treinen rijden tussen Workum en Stavoren. Dat zegt ProRail. Sinds 13 maart rijden er geen treinen op dat traject omdat in de Friese plaats Molkweru… ",
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "Transfery.info",
        title: "Reprezentacja Polski: Prawdopodobny skład na mecz z Czechami - Transfery.info",
        description:
            "De dreigende bankencrisis is voor de Amerikaanse centrale bank geen reden om de rente niet verder te verhogen, de strijd tegen de hoge inflatie is nog niet gestreden.",
        url: "https://news.google.com/rss/articles/CBMiZWh0dHBzOi8vdHJhbnNmZXJ5LmluZm8vYWt0dWFsbm9zY2kvcmVwcmV6ZW50YWNqYS1wb2xza2ktcHJhd2RvcG9kb2JueS1za2xhZC1uYS1tZWN6LXotY3plY2hhbWkvMTgyMTIx0gFpaHR0cHM6Ly90cmFuc2ZlcnkuaW5mby9hbXAvYWt0dWFsbm9zY2kvcmVwcmV6ZW50YWNqYS1wb2xza2ktcHJhd2RvcG9kb2JueS1za2xhZC1uYS1tZWN6LXotY3plY2hhbWkvMTgyMTIx?oc=5",
        urlToImage: "https://cdn.nos.nl/image/2023/03/22/954103/1024x576a.jpg",
        publishedAt: "2023-03-23T07:53:15Z",
        content:
            "De Fed, de Amerikaanse centrale bank, heeft de rente opnieuw verhoogd, met 0,25 procentpunt. De belangrijkste beleidsrente in de VS staat nu op 4,75 tot 5 procent. De renteverhoging is bedoeld om de … [+2343 chars]",
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "Pudelek",
        title: 'Tak Joanna Opozda wyglądała jeszcze kilka lat temu w JASNYM BLONDZIE: "Właśnie dlatego już nie rozjaśniam włosów" (FOTO) - Pudelek',
        description: null,
        url: "https://news.google.com/rss/articles/CBMinAFodHRwczovL3d3dy5wdWRlbGVrLnBsL3Rhay1qb2FubmEtb3BvemRhLXd5Z2xhZGFsYS1qZXN6Y3plLWtpbGthLWxhdC10ZW11LXctamFzbnltLWJsb25kemllLXdsYXNuaWUtZGxhdGVnby1qdXotbmllLXJvemphc25pYW0td2xvc293LWZvdG8tNjg3OTQ1MjA3NDEzODQzMmHSAaIBaHR0cHM6Ly93d3cucHVkZWxlay5wbC90YWstam9hbm5hLW9wb3pkYS13eWdsYWRhbGEtamVzemN6ZS1raWxrYS1sYXQtdGVtdS13LWphc255bS1ibG9uZHppZS13bGFzbmllLWRsYXRlZ28tanV6LW5pZS1yb3pqYXNuaWFtLXdsb3Nvdy1mb3RvLTY4Nzk0NTIwNzQxMzg0MzJhP2FtcD0x?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:40:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "Money.pl",
        title: "Podatek od trzynastej emerytury. Cześć seniorów odzyska pieniądze. Oto sposób - Money.pl",
        description: null,
        url: "https://news.google.com/rss/articles/CBMigQFodHRwczovL3d3dy5tb25leS5wbC9lbWVyeXR1cnkvcG9kYXRlay1vZC10cnp5bmFzdGVqLWVtZXJ5dHVyeS1jemVzYy1zZW5pb3Jvdy1vZHp5c2thLXBpZW5pYWR6ZS1vdG8tc3Bvc29iLTY4Nzk0NjUwNTI4NjczOTJhLmh0bWzSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:34:51Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "TVP Info",
        title: "Zandberg odpowiada Tuskowi: Neoliberalizm skończył się przejęciem władzy przez PiS - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMidmh0dHBzOi8vd3d3LnR2cC5pbmZvLzY4Njc5MDk5L2Fkcmlhbi16YW5kYmVyZy1vZHBvd2lhZGEtdHVza293aS1uZW9saWJlcmFsaXptLXNrb25jenlsLXNpZS1wcnplamVjaWVtLXdsYWR6eS1wcnplei1waXPSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:27:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "PAP",
        title: "MSZ: wizyta księcia Williama w Polsce poświęcona jest przede wszystkim wsparciu dla Ukrainy i Polski - PAP",
        description: null,
        url: "https://news.google.com/rss/articles/CBMidWh0dHBzOi8vd3d3LnBhcC5wbC9ha3R1YWxub3NjaS9uZXdzJTJDMTU1MTgyMSUyQ21zei13aXp5dGEta3NpZWNpYS13aWxsaWFtYS13LXBvbHNjZS1wb3N3aWVjb25hLWplc3QtcHJ6ZWRlLXdzenlzdGtpbdIBAA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:23:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "Money.pl",
        title: "Branża drzewna w tarapatach. Przemysł traci swoją konkurencyjność - Money.pl",
        description: null,
        url: "https://news.google.com/rss/articles/CBMic2h0dHBzOi8vd3d3Lm1vbmV5LnBsL2dpZWxkYS9icmFuemEtZHJ6ZXduYS13LXRhcmFwYXRhY2gtcHJ6ZW15c2wtdHJhY2ktc3dvamEta29ua3VyZW5jeWpub3NjLTY4Nzk0NTgxNDM0NTYwMzJhLmh0bWzSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:06:47Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "Onet",
        title: "Córka Cruise'a idzie do college'u. Aktor od 10 lat nie odzywa się do Suri - Onet",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiggFodHRwczovL3d3dy5vbmV0LnBsL3N0eWwtenljaWEvb25ldGtvYmlldGEvY29ya2EtY3J1aXNlYS1pZHppZS1kby1jb2xsZWdldS1ha3Rvci1vZC0xMC1sYXQtbmllLW9kenl3YS1zaWUtZG8tc3VyaS9sMnk3MHN0LDJiODMzNzhh0gEA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:02:20Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "WP Wiadomości",
        title: "Wierny pies Putina. Miedwiediew znów próbuje siać zamęt - WP Wiadomości",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiYWh0dHBzOi8vd2lhZG9tb3NjaS53cC5wbC93aWVybnktcGllcy1wdXRpbmEtbWllZHdpZWRpZXctem5vdy1wcm9idWplLXNpYWMtemFtZXQtNjg3OTQ1MzE4NDYxMzE1MmHSAWdodHRwczovL3dpYWRvbW9zY2kud3AucGwvd2llcm55LXBpZXMtcHV0aW5hLW1pZWR3aWVkaWV3LXpub3ctcHJvYnVqZS1zaWFjLXphbWV0LTY4Nzk0NTMxODQ2MTMxNTJhP2FtcD0x?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:02:04Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "TVP Info",
        title: "Niemiecki koncern na liście „międzynarodowych sponsorów wojny” - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMihQFodHRwczovL3d3dy50dnAuaW5mby82ODY3ODQzMS9uaWVtaWVja2ktZ2lnYW50LW1ldHJvLWFnLW5hZGFsLWR6aWFsYS13LXJvc2ppLWtvbmNlcm4tdHJhZmlsLW5hLWxpc3RlLW1pZWR6eW5hcm9kb3d5Y2gtc3BvbnNvcm93LXdvam550gEA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:00:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "Wp.pl",
        title: 'Jarek przeszedł metamorfozę? "Ja mam kondycję" - Wp.pl',
        description: null,
        url: "https://news.google.com/rss/articles/CBMiU2h0dHBzOi8va29iaWV0YS53cC5wbC9qYXJlay1wcnplc3plZGwtbWV0YW1vcmZvemUtamEtbWFtLWtvbmR5Y2plLTY4Nzk0NTUzNTAzNjkwNTZh0gFZaHR0cHM6Ly9rb2JpZXRhLndwLnBsL2phcmVrLXByemVzemVkbC1tZXRhbW9yZm96ZS1qYS1tYW0ta29uZHljamUtNjg3OTQ1NTM1MDM2OTA1NmE_YW1wPTE?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:55:25Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "TVP Info",
        title: "Republikański kontrkandydat Trumpa: Putin to zbrodniarz, trzeba go rozliczyć - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMibGh0dHBzOi8vd3d3LnR2cC5pbmZvLzY4Njc1NTM0L3VzYS1kZXNhbnRpcy1wdXRpbi1qZXN0LXpicm9kbmlhcnplbS13b2plbm55bS1rdG9yeS1wb3dpbmllbi16b3N0YWMtcm96bGljem9uedIBAA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:46:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "Sportowefakty",
        title: 'Wskazała powód słabszej dyspozycji Igi Świątek. "Myślę, że to nasza wina" - Sportowefakty',
        description: null,
        url: "https://news.google.com/rss/articles/CBMib2h0dHBzOi8vc3BvcnRvd2VmYWt0eS53cC5wbC90ZW5pcy8xMDUxNTYzL3dza2F6YWxhLXBvd29kLXNsYWJzemVqLWR5c3BvenljamktaWdpLXN3aWF0ZWstbXlzbGUtemUtdG8tbmFzemEtd2luYdIBc2h0dHBzOi8vc3BvcnRvd2VmYWt0eS53cC5wbC9hbXAvdGVuaXMvMTA1MTU2My93c2themFsYS1wb3dvZC1zbGFic3plai1keXNwb3p5Y2ppLWlnaS1zd2lhdGVrLW15c2xlLXplLXRvLW5hc3phLXdpbmE?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:40:49Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "TVP Info",
        title: "Ponad 25 tys. zł kary dla szpitala, w którym pracuje Mama Ginekolog - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMijAFodHRwczovL3d3dy50dnAuaW5mby82ODY3ODA3Ni9uZnotcG9uYWQtMjUtdHlzLXpsLWthcnktZGxhLXN6cGl0YWxhLXcta3RvcnltLXByYWN1amUtbWFtYS1naW5la29sb2ctemEtbmllc2x1c3puaWUtcm96bGljem9uYS1ob3NwaXRhbGl6YWNqZdIBAA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:40:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "Do Rzeczy",
        title: "Ukraina. Ostrzał Zaporoża. Uszkodzonych ponad 300 mieszkań - Do Rzeczy",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiXmh0dHBzOi8vZG9yemVjenkucGwvc3dpYXQvNDE5NDc5L3VrcmFpbmEtb3N0cnphbC16YXBvcm96YS11c3prb2R6b255Y2gtcG9uYWQtMzAwLW1pZXN6a2FuLmh0bWzSAVxodHRwczovL2RvcnplY3p5LnBsL2FtcC80MTk0NzkvdWtyYWluYS1vc3RyemFsLXphcG9yb3phLXVzemtvZHpvbnljaC1wb25hZC0zMDAtbWllc3prYW4uaHRtbA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:13:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "BusinessInsider",
        title: "Ile zarabiają policjanci? Za mało. Zwłaszcza w dużych miastach odchodzą na potęgę - BusinessInsider",
        description: null,
        url: "https://news.google.com/rss/articles/CBMigQFodHRwczovL2J1c2luZXNzaW5zaWRlci5jb20ucGwvd2lhZG9tb3NjaS9pbGUtemFyYWJpYWphLXBvbGljamFuY2ktemEtbWFsby16d2xhc3pjemEtdy1kdXp5Y2gtbWlhc3RhY2gtb2RjaG9kemEtbmEtcG90ZWdlL2Zwam1nNnnSAYUBaHR0cHM6Ly9idXNpbmVzc2luc2lkZXIuY29tLnBsL3dpYWRvbW9zY2kvaWxlLXphcmFiaWFqYS1wb2xpY2phbmNpLXphLW1hbG8tendsYXN6Y3phLXctZHV6eWNoLW1pYXN0YWNoLW9kY2hvZHphLW5hLXBvdGVnZS9mcGptZzZ5LmFtcA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:01:29Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "BusinessInsider",
        title: "Fed widzi, że banki padają. W efekcie podniesie stopy procentowe jeszcze tylko raz - BusinessInsider",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiggFodHRwczovL2J1c2luZXNzaW5zaWRlci5jb20ucGwvZ29zcG9kYXJrYS9mZWQtd2lkemktemUtYmFua2ktcGFkYWphLXctZWZla2NpZS1wb2RuaWVzaWUtc3RvcHktcHJvY2VudG93ZS1qZXN6Y3plLXR5bGtvLXJhei92cHQ0dHBy0gGGAWh0dHBzOi8vYnVzaW5lc3NpbnNpZGVyLmNvbS5wbC9nb3Nwb2RhcmthL2ZlZC13aWR6aS16ZS1iYW5raS1wYWRhamEtdy1lZmVrY2llLXBvZG5pZXNpZS1zdG9weS1wcm9jZW50b3dlLWplc3pjemUtdHlsa28tcmF6L3ZwdDR0cHIuYW1w?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T05:53:28Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "Gazeta Wyborcza",
        title: "Wielka afera ze sprzętem przeciw COVID-19. Kto w obozie władzy za nią odpowie? - Gazeta Wyborcza",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiZ2h0dHBzOi8vd3lib3JjemEucGwvNyw3NTM5OCwyOTU4NjIwMyx3aWVsa2EtYWZlcmEtemUtc3ByemV0ZW0tcHJ6ZWNpdy1jb3ZpZC0xOS1rdG8tdy1vYm96aWUtd2xhZHp5Lmh0bWzSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T05:00:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "Interia Biznes",
        title: "Google przedstawił Barda. Na razie tylko w USA i Wielkiej Brytanii - Interia Biznes",
        description: null,
        url: "https://news.google.com/rss/articles/CBMicmh0dHBzOi8vYml6bmVzLmludGVyaWEucGwvZ29zcG9kYXJrYS9uZXdzLWdvb2dsZS1wcnplZHN0YXdpbC1iYXJkYS1uYS1yYXppZS10eWxrby13LXVzYS1pLXdpZWxraWVqLWJyeSxuSWQsNjY3MTAxMNIBdWh0dHBzOi8vYml6bmVzLmludGVyaWEucGwvZ29zcG9kYXJrYS9uZXdzYW1wLWdvb2dsZS1wcnplZHN0YXdpbC1iYXJkYS1uYS1yYXppZS10eWxrby13LXVzYS1pLXdpZWxraWVqLWJyeSxuSWQsNjY3MTAxMA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T05:00:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNamePL,
        },
        author: "TVN24",
        title: "Atak Rosji na Ukrainę. Relacja na żywo 23 marca 2023 - TVN24",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiUmh0dHBzOi8vdHZuMjQucGwvc3dpYXQvYXRhay1yb3NqaS1uYS11a3JhaW5lLXJlbGFjamEtbmEtenl3by0yMy1tYXJjYS0yMDIzLTY4NTY3MTDSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T04:35:00Z",
        content: null,
    },
];
export const sourceNameFR = "fake source name FR";
export const articlesFR = [
    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "Onet",
        title: "Przełom w sprawie wycieczek młodzieży z Izraela. Jest umowa - Onet",
        description: null,
        url: "https://news.google.com/rss/articles/CBMicmh0dHBzOi8vd3d3Lm9uZXQucGwvaW5mb3JtYWNqZS9vbmV0d2lhZG9tb3NjaS9qZXN0LXVtb3dhLXotaXpyYWVsZW0tdy1zcHJhd2llLXd5Y2llY3play1tbG9kemllenkvczVta2dxaCw3OWNmYzI3ONIBAA?oc=5",
        urlToImage:
            "https://www.rtlboulevard.nl/sites/default/files/content/images/2023/03/22/Schermafbeelding%202023-03-22%20om%2021.57.37.jpg?itok=K3Z_MbbH&offsetX=0&offsetY=0&cropWidth=1681&cropHeight=946&width=2048&height=1152&impolicy=dynamic",
        publishedAt: "2023-03-23T08:17:54Z",
        content:
            "Over ruim een maand, vanaf 24 april, kunnen er weer treinen rijden tussen Workum en Stavoren. Dat zegt ProRail. Sinds 13 maart rijden er geen treinen op dat traject omdat in de Friese plaats Molkweru… ",
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "Transfery.info",
        title: "Reprezentacja Polski: Prawdopodobny skład na mecz z Czechami - Transfery.info",
        description:
            "De dreigende bankencrisis is voor de Amerikaanse centrale bank geen reden om de rente niet verder te verhogen, de strijd tegen de hoge inflatie is nog niet gestreden.",
        url: "https://news.google.com/rss/articles/CBMiZWh0dHBzOi8vdHJhbnNmZXJ5LmluZm8vYWt0dWFsbm9zY2kvcmVwcmV6ZW50YWNqYS1wb2xza2ktcHJhd2RvcG9kb2JueS1za2xhZC1uYS1tZWN6LXotY3plY2hhbWkvMTgyMTIx0gFpaHR0cHM6Ly90cmFuc2ZlcnkuaW5mby9hbXAvYWt0dWFsbm9zY2kvcmVwcmV6ZW50YWNqYS1wb2xza2ktcHJhd2RvcG9kb2JueS1za2xhZC1uYS1tZWN6LXotY3plY2hhbWkvMTgyMTIx?oc=5",
        urlToImage: "https://cdn.nos.nl/image/2023/03/22/954103/1024x576a.jpg",
        publishedAt: "2023-03-23T07:53:15Z",
        content:
            "De Fed, de Amerikaanse centrale bank, heeft de rente opnieuw verhoogd, met 0,25 procentpunt. De belangrijkste beleidsrente in de VS staat nu op 4,75 tot 5 procent. De renteverhoging is bedoeld om de … [+2343 chars]",
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "Pudelek",
        title: 'Tak Joanna Opozda wyglądała jeszcze kilka lat temu w JASNYM BLONDZIE: "Właśnie dlatego już nie rozjaśniam włosów" (FOTO) - Pudelek',
        description: null,
        url: "https://news.google.com/rss/articles/CBMinAFodHRwczovL3d3dy5wdWRlbGVrLnBsL3Rhay1qb2FubmEtb3BvemRhLXd5Z2xhZGFsYS1qZXN6Y3plLWtpbGthLWxhdC10ZW11LXctamFzbnltLWJsb25kemllLXdsYXNuaWUtZGxhdGVnby1qdXotbmllLXJvemphc25pYW0td2xvc293LWZvdG8tNjg3OTQ1MjA3NDEzODQzMmHSAaIBaHR0cHM6Ly93d3cucHVkZWxlay5wbC90YWstam9hbm5hLW9wb3pkYS13eWdsYWRhbGEtamVzemN6ZS1raWxrYS1sYXQtdGVtdS13LWphc255bS1ibG9uZHppZS13bGFzbmllLWRsYXRlZ28tanV6LW5pZS1yb3pqYXNuaWFtLXdsb3Nvdy1mb3RvLTY4Nzk0NTIwNzQxMzg0MzJhP2FtcD0x?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:40:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "Money.pl",
        title: "Podatek od trzynastej emerytury. Cześć seniorów odzyska pieniądze. Oto sposób - Money.pl",
        description: null,
        url: "https://news.google.com/rss/articles/CBMigQFodHRwczovL3d3dy5tb25leS5wbC9lbWVyeXR1cnkvcG9kYXRlay1vZC10cnp5bmFzdGVqLWVtZXJ5dHVyeS1jemVzYy1zZW5pb3Jvdy1vZHp5c2thLXBpZW5pYWR6ZS1vdG8tc3Bvc29iLTY4Nzk0NjUwNTI4NjczOTJhLmh0bWzSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:34:51Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "TVP Info",
        title: "Zandberg odpowiada Tuskowi: Neoliberalizm skończył się przejęciem władzy przez PiS - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMidmh0dHBzOi8vd3d3LnR2cC5pbmZvLzY4Njc5MDk5L2Fkcmlhbi16YW5kYmVyZy1vZHBvd2lhZGEtdHVza293aS1uZW9saWJlcmFsaXptLXNrb25jenlsLXNpZS1wcnplamVjaWVtLXdsYWR6eS1wcnplei1waXPSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:27:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "PAP",
        title: "MSZ: wizyta księcia Williama w Polsce poświęcona jest przede wszystkim wsparciu dla Ukrainy i Polski - PAP",
        description: null,
        url: "https://news.google.com/rss/articles/CBMidWh0dHBzOi8vd3d3LnBhcC5wbC9ha3R1YWxub3NjaS9uZXdzJTJDMTU1MTgyMSUyQ21zei13aXp5dGEta3NpZWNpYS13aWxsaWFtYS13LXBvbHNjZS1wb3N3aWVjb25hLWplc3QtcHJ6ZWRlLXdzenlzdGtpbdIBAA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:23:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "Money.pl",
        title: "Branża drzewna w tarapatach. Przemysł traci swoją konkurencyjność - Money.pl",
        description: null,
        url: "https://news.google.com/rss/articles/CBMic2h0dHBzOi8vd3d3Lm1vbmV5LnBsL2dpZWxkYS9icmFuemEtZHJ6ZXduYS13LXRhcmFwYXRhY2gtcHJ6ZW15c2wtdHJhY2ktc3dvamEta29ua3VyZW5jeWpub3NjLTY4Nzk0NTgxNDM0NTYwMzJhLmh0bWzSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:06:47Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "Onet",
        title: "Córka Cruise'a idzie do college'u. Aktor od 10 lat nie odzywa się do Suri - Onet",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiggFodHRwczovL3d3dy5vbmV0LnBsL3N0eWwtenljaWEvb25ldGtvYmlldGEvY29ya2EtY3J1aXNlYS1pZHppZS1kby1jb2xsZWdldS1ha3Rvci1vZC0xMC1sYXQtbmllLW9kenl3YS1zaWUtZG8tc3VyaS9sMnk3MHN0LDJiODMzNzhh0gEA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:02:20Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "WP Wiadomości",
        title: "Wierny pies Putina. Miedwiediew znów próbuje siać zamęt - WP Wiadomości",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiYWh0dHBzOi8vd2lhZG9tb3NjaS53cC5wbC93aWVybnktcGllcy1wdXRpbmEtbWllZHdpZWRpZXctem5vdy1wcm9idWplLXNpYWMtemFtZXQtNjg3OTQ1MzE4NDYxMzE1MmHSAWdodHRwczovL3dpYWRvbW9zY2kud3AucGwvd2llcm55LXBpZXMtcHV0aW5hLW1pZWR3aWVkaWV3LXpub3ctcHJvYnVqZS1zaWFjLXphbWV0LTY4Nzk0NTMxODQ2MTMxNTJhP2FtcD0x?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:02:04Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "TVP Info",
        title: "Niemiecki koncern na liście „międzynarodowych sponsorów wojny” - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMihQFodHRwczovL3d3dy50dnAuaW5mby82ODY3ODQzMS9uaWVtaWVja2ktZ2lnYW50LW1ldHJvLWFnLW5hZGFsLWR6aWFsYS13LXJvc2ppLWtvbmNlcm4tdHJhZmlsLW5hLWxpc3RlLW1pZWR6eW5hcm9kb3d5Y2gtc3BvbnNvcm93LXdvam550gEA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:00:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "Wp.pl",
        title: 'Jarek przeszedł metamorfozę? "Ja mam kondycję" - Wp.pl',
        description: null,
        url: "https://news.google.com/rss/articles/CBMiU2h0dHBzOi8va29iaWV0YS53cC5wbC9qYXJlay1wcnplc3plZGwtbWV0YW1vcmZvemUtamEtbWFtLWtvbmR5Y2plLTY4Nzk0NTUzNTAzNjkwNTZh0gFZaHR0cHM6Ly9rb2JpZXRhLndwLnBsL2phcmVrLXByemVzemVkbC1tZXRhbW9yZm96ZS1qYS1tYW0ta29uZHljamUtNjg3OTQ1NTM1MDM2OTA1NmE_YW1wPTE?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:55:25Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "TVP Info",
        title: "Republikański kontrkandydat Trumpa: Putin to zbrodniarz, trzeba go rozliczyć - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMibGh0dHBzOi8vd3d3LnR2cC5pbmZvLzY4Njc1NTM0L3VzYS1kZXNhbnRpcy1wdXRpbi1qZXN0LXpicm9kbmlhcnplbS13b2plbm55bS1rdG9yeS1wb3dpbmllbi16b3N0YWMtcm96bGljem9uedIBAA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:46:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "Sportowefakty",
        title: 'Wskazała powód słabszej dyspozycji Igi Świątek. "Myślę, że to nasza wina" - Sportowefakty',
        description: null,
        url: "https://news.google.com/rss/articles/CBMib2h0dHBzOi8vc3BvcnRvd2VmYWt0eS53cC5wbC90ZW5pcy8xMDUxNTYzL3dza2F6YWxhLXBvd29kLXNsYWJzemVqLWR5c3BvenljamktaWdpLXN3aWF0ZWstbXlzbGUtemUtdG8tbmFzemEtd2luYdIBc2h0dHBzOi8vc3BvcnRvd2VmYWt0eS53cC5wbC9hbXAvdGVuaXMvMTA1MTU2My93c2themFsYS1wb3dvZC1zbGFic3plai1keXNwb3p5Y2ppLWlnaS1zd2lhdGVrLW15c2xlLXplLXRvLW5hc3phLXdpbmE?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:40:49Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "TVP Info",
        title: "Ponad 25 tys. zł kary dla szpitala, w którym pracuje Mama Ginekolog - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMijAFodHRwczovL3d3dy50dnAuaW5mby82ODY3ODA3Ni9uZnotcG9uYWQtMjUtdHlzLXpsLWthcnktZGxhLXN6cGl0YWxhLXcta3RvcnltLXByYWN1amUtbWFtYS1naW5la29sb2ctemEtbmllc2x1c3puaWUtcm96bGljem9uYS1ob3NwaXRhbGl6YWNqZdIBAA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:40:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "Do Rzeczy",
        title: "Ukraina. Ostrzał Zaporoża. Uszkodzonych ponad 300 mieszkań - Do Rzeczy",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiXmh0dHBzOi8vZG9yemVjenkucGwvc3dpYXQvNDE5NDc5L3VrcmFpbmEtb3N0cnphbC16YXBvcm96YS11c3prb2R6b255Y2gtcG9uYWQtMzAwLW1pZXN6a2FuLmh0bWzSAVxodHRwczovL2RvcnplY3p5LnBsL2FtcC80MTk0NzkvdWtyYWluYS1vc3RyemFsLXphcG9yb3phLXVzemtvZHpvbnljaC1wb25hZC0zMDAtbWllc3prYW4uaHRtbA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:13:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "BusinessInsider",
        title: "Ile zarabiają policjanci? Za mało. Zwłaszcza w dużych miastach odchodzą na potęgę - BusinessInsider",
        description: null,
        url: "https://news.google.com/rss/articles/CBMigQFodHRwczovL2J1c2luZXNzaW5zaWRlci5jb20ucGwvd2lhZG9tb3NjaS9pbGUtemFyYWJpYWphLXBvbGljamFuY2ktemEtbWFsby16d2xhc3pjemEtdy1kdXp5Y2gtbWlhc3RhY2gtb2RjaG9kemEtbmEtcG90ZWdlL2Zwam1nNnnSAYUBaHR0cHM6Ly9idXNpbmVzc2luc2lkZXIuY29tLnBsL3dpYWRvbW9zY2kvaWxlLXphcmFiaWFqYS1wb2xpY2phbmNpLXphLW1hbG8tendsYXN6Y3phLXctZHV6eWNoLW1pYXN0YWNoLW9kY2hvZHphLW5hLXBvdGVnZS9mcGptZzZ5LmFtcA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:01:29Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "BusinessInsider",
        title: "Fed widzi, że banki padają. W efekcie podniesie stopy procentowe jeszcze tylko raz - BusinessInsider",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiggFodHRwczovL2J1c2luZXNzaW5zaWRlci5jb20ucGwvZ29zcG9kYXJrYS9mZWQtd2lkemktemUtYmFua2ktcGFkYWphLXctZWZla2NpZS1wb2RuaWVzaWUtc3RvcHktcHJvY2VudG93ZS1qZXN6Y3plLXR5bGtvLXJhei92cHQ0dHBy0gGGAWh0dHBzOi8vYnVzaW5lc3NpbnNpZGVyLmNvbS5wbC9nb3Nwb2RhcmthL2ZlZC13aWR6aS16ZS1iYW5raS1wYWRhamEtdy1lZmVrY2llLXBvZG5pZXNpZS1zdG9weS1wcm9jZW50b3dlLWplc3pjemUtdHlsa28tcmF6L3ZwdDR0cHIuYW1w?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T05:53:28Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "Gazeta Wyborcza",
        title: "Wielka afera ze sprzętem przeciw COVID-19. Kto w obozie władzy za nią odpowie? - Gazeta Wyborcza",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiZ2h0dHBzOi8vd3lib3JjemEucGwvNyw3NTM5OCwyOTU4NjIwMyx3aWVsa2EtYWZlcmEtemUtc3ByemV0ZW0tcHJ6ZWNpdy1jb3ZpZC0xOS1rdG8tdy1vYm96aWUtd2xhZHp5Lmh0bWzSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T05:00:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "Interia Biznes",
        title: "Google przedstawił Barda. Na razie tylko w USA i Wielkiej Brytanii - Interia Biznes",
        description: null,
        url: "https://news.google.com/rss/articles/CBMicmh0dHBzOi8vYml6bmVzLmludGVyaWEucGwvZ29zcG9kYXJrYS9uZXdzLWdvb2dsZS1wcnplZHN0YXdpbC1iYXJkYS1uYS1yYXppZS10eWxrby13LXVzYS1pLXdpZWxraWVqLWJyeSxuSWQsNjY3MTAxMNIBdWh0dHBzOi8vYml6bmVzLmludGVyaWEucGwvZ29zcG9kYXJrYS9uZXdzYW1wLWdvb2dsZS1wcnplZHN0YXdpbC1iYXJkYS1uYS1yYXppZS10eWxrby13LXVzYS1pLXdpZWxraWVqLWJyeSxuSWQsNjY3MTAxMA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T05:00:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameFR,
        },
        author: "TVN24",
        title: "Atak Rosji na Ukrainę. Relacja na żywo 23 marca 2023 - TVN24",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiUmh0dHBzOi8vdHZuMjQucGwvc3dpYXQvYXRhay1yb3NqaS1uYS11a3JhaW5lLXJlbGFjamEtbmEtenl3by0yMy1tYXJjYS0yMDIzLTY4NTY3MTDSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T04:35:00Z",
        content: null,
    },
];
export const sourceNameBR = "fake source name BR";
export const articlesBR = [
    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "Onet",
        title: "Przełom w sprawie wycieczek młodzieży z Izraela. Jest umowa - Onet",
        description: null,
        url: "https://news.google.com/rss/articles/CBMicmh0dHBzOi8vd3d3Lm9uZXQucGwvaW5mb3JtYWNqZS9vbmV0d2lhZG9tb3NjaS9qZXN0LXVtb3dhLXotaXpyYWVsZW0tdy1zcHJhd2llLXd5Y2llY3play1tbG9kemllenkvczVta2dxaCw3OWNmYzI3ONIBAA?oc=5",
        urlToImage:
            "https://www.rtlboulevard.nl/sites/default/files/content/images/2023/03/22/Schermafbeelding%202023-03-22%20om%2021.57.37.jpg?itok=K3Z_MbbH&offsetX=0&offsetY=0&cropWidth=1681&cropHeight=946&width=2048&height=1152&impolicy=dynamic",
        publishedAt: "2023-03-23T08:17:54Z",
        content:
            "Over ruim een maand, vanaf 24 april, kunnen er weer treinen rijden tussen Workum en Stavoren. Dat zegt ProRail. Sinds 13 maart rijden er geen treinen op dat traject omdat in de Friese plaats Molkweru… ",
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "Transfery.info",
        title: "Reprezentacja Polski: Prawdopodobny skład na mecz z Czechami - Transfery.info",
        description:
            "De dreigende bankencrisis is voor de Amerikaanse centrale bank geen reden om de rente niet verder te verhogen, de strijd tegen de hoge inflatie is nog niet gestreden.",
        url: "https://news.google.com/rss/articles/CBMiZWh0dHBzOi8vdHJhbnNmZXJ5LmluZm8vYWt0dWFsbm9zY2kvcmVwcmV6ZW50YWNqYS1wb2xza2ktcHJhd2RvcG9kb2JueS1za2xhZC1uYS1tZWN6LXotY3plY2hhbWkvMTgyMTIx0gFpaHR0cHM6Ly90cmFuc2ZlcnkuaW5mby9hbXAvYWt0dWFsbm9zY2kvcmVwcmV6ZW50YWNqYS1wb2xza2ktcHJhd2RvcG9kb2JueS1za2xhZC1uYS1tZWN6LXotY3plY2hhbWkvMTgyMTIx?oc=5",
        urlToImage: "https://cdn.nos.nl/image/2023/03/22/954103/1024x576a.jpg",
        publishedAt: "2023-03-23T07:53:15Z",
        content:
            "De Fed, de Amerikaanse centrale bank, heeft de rente opnieuw verhoogd, met 0,25 procentpunt. De belangrijkste beleidsrente in de VS staat nu op 4,75 tot 5 procent. De renteverhoging is bedoeld om de … [+2343 chars]",
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "Pudelek",
        title: 'Tak Joanna Opozda wyglądała jeszcze kilka lat temu w JASNYM BLONDZIE: "Właśnie dlatego już nie rozjaśniam włosów" (FOTO) - Pudelek',
        description: null,
        url: "https://news.google.com/rss/articles/CBMinAFodHRwczovL3d3dy5wdWRlbGVrLnBsL3Rhay1qb2FubmEtb3BvemRhLXd5Z2xhZGFsYS1qZXN6Y3plLWtpbGthLWxhdC10ZW11LXctamFzbnltLWJsb25kemllLXdsYXNuaWUtZGxhdGVnby1qdXotbmllLXJvemphc25pYW0td2xvc293LWZvdG8tNjg3OTQ1MjA3NDEzODQzMmHSAaIBaHR0cHM6Ly93d3cucHVkZWxlay5wbC90YWstam9hbm5hLW9wb3pkYS13eWdsYWRhbGEtamVzemN6ZS1raWxrYS1sYXQtdGVtdS13LWphc255bS1ibG9uZHppZS13bGFzbmllLWRsYXRlZ28tanV6LW5pZS1yb3pqYXNuaWFtLXdsb3Nvdy1mb3RvLTY4Nzk0NTIwNzQxMzg0MzJhP2FtcD0x?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:40:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "Money.pl",
        title: "Podatek od trzynastej emerytury. Cześć seniorów odzyska pieniądze. Oto sposób - Money.pl",
        description: null,
        url: "https://news.google.com/rss/articles/CBMigQFodHRwczovL3d3dy5tb25leS5wbC9lbWVyeXR1cnkvcG9kYXRlay1vZC10cnp5bmFzdGVqLWVtZXJ5dHVyeS1jemVzYy1zZW5pb3Jvdy1vZHp5c2thLXBpZW5pYWR6ZS1vdG8tc3Bvc29iLTY4Nzk0NjUwNTI4NjczOTJhLmh0bWzSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:34:51Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "TVP Info",
        title: "Zandberg odpowiada Tuskowi: Neoliberalizm skończył się przejęciem władzy przez PiS - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMidmh0dHBzOi8vd3d3LnR2cC5pbmZvLzY4Njc5MDk5L2Fkcmlhbi16YW5kYmVyZy1vZHBvd2lhZGEtdHVza293aS1uZW9saWJlcmFsaXptLXNrb25jenlsLXNpZS1wcnplamVjaWVtLXdsYWR6eS1wcnplei1waXPSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:27:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "PAP",
        title: "MSZ: wizyta księcia Williama w Polsce poświęcona jest przede wszystkim wsparciu dla Ukrainy i Polski - PAP",
        description: null,
        url: "https://news.google.com/rss/articles/CBMidWh0dHBzOi8vd3d3LnBhcC5wbC9ha3R1YWxub3NjaS9uZXdzJTJDMTU1MTgyMSUyQ21zei13aXp5dGEta3NpZWNpYS13aWxsaWFtYS13LXBvbHNjZS1wb3N3aWVjb25hLWplc3QtcHJ6ZWRlLXdzenlzdGtpbdIBAA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:23:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "Money.pl",
        title: "Branża drzewna w tarapatach. Przemysł traci swoją konkurencyjność - Money.pl",
        description: null,
        url: "https://news.google.com/rss/articles/CBMic2h0dHBzOi8vd3d3Lm1vbmV5LnBsL2dpZWxkYS9icmFuemEtZHJ6ZXduYS13LXRhcmFwYXRhY2gtcHJ6ZW15c2wtdHJhY2ktc3dvamEta29ua3VyZW5jeWpub3NjLTY4Nzk0NTgxNDM0NTYwMzJhLmh0bWzSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:06:47Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "Onet",
        title: "Córka Cruise'a idzie do college'u. Aktor od 10 lat nie odzywa się do Suri - Onet",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiggFodHRwczovL3d3dy5vbmV0LnBsL3N0eWwtenljaWEvb25ldGtvYmlldGEvY29ya2EtY3J1aXNlYS1pZHppZS1kby1jb2xsZWdldS1ha3Rvci1vZC0xMC1sYXQtbmllLW9kenl3YS1zaWUtZG8tc3VyaS9sMnk3MHN0LDJiODMzNzhh0gEA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:02:20Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "WP Wiadomości",
        title: "Wierny pies Putina. Miedwiediew znów próbuje siać zamęt - WP Wiadomości",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiYWh0dHBzOi8vd2lhZG9tb3NjaS53cC5wbC93aWVybnktcGllcy1wdXRpbmEtbWllZHdpZWRpZXctem5vdy1wcm9idWplLXNpYWMtemFtZXQtNjg3OTQ1MzE4NDYxMzE1MmHSAWdodHRwczovL3dpYWRvbW9zY2kud3AucGwvd2llcm55LXBpZXMtcHV0aW5hLW1pZWR3aWVkaWV3LXpub3ctcHJvYnVqZS1zaWFjLXphbWV0LTY4Nzk0NTMxODQ2MTMxNTJhP2FtcD0x?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:02:04Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "TVP Info",
        title: "Niemiecki koncern na liście „międzynarodowych sponsorów wojny” - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMihQFodHRwczovL3d3dy50dnAuaW5mby82ODY3ODQzMS9uaWVtaWVja2ktZ2lnYW50LW1ldHJvLWFnLW5hZGFsLWR6aWFsYS13LXJvc2ppLWtvbmNlcm4tdHJhZmlsLW5hLWxpc3RlLW1pZWR6eW5hcm9kb3d5Y2gtc3BvbnNvcm93LXdvam550gEA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T07:00:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "Wp.pl",
        title: 'Jarek przeszedł metamorfozę? "Ja mam kondycję" - Wp.pl',
        description: null,
        url: "https://news.google.com/rss/articles/CBMiU2h0dHBzOi8va29iaWV0YS53cC5wbC9qYXJlay1wcnplc3plZGwtbWV0YW1vcmZvemUtamEtbWFtLWtvbmR5Y2plLTY4Nzk0NTUzNTAzNjkwNTZh0gFZaHR0cHM6Ly9rb2JpZXRhLndwLnBsL2phcmVrLXByemVzemVkbC1tZXRhbW9yZm96ZS1qYS1tYW0ta29uZHljamUtNjg3OTQ1NTM1MDM2OTA1NmE_YW1wPTE?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:55:25Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "TVP Info",
        title: "Republikański kontrkandydat Trumpa: Putin to zbrodniarz, trzeba go rozliczyć - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMibGh0dHBzOi8vd3d3LnR2cC5pbmZvLzY4Njc1NTM0L3VzYS1kZXNhbnRpcy1wdXRpbi1qZXN0LXpicm9kbmlhcnplbS13b2plbm55bS1rdG9yeS1wb3dpbmllbi16b3N0YWMtcm96bGljem9uedIBAA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:46:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "Sportowefakty",
        title: 'Wskazała powód słabszej dyspozycji Igi Świątek. "Myślę, że to nasza wina" - Sportowefakty',
        description: null,
        url: "https://news.google.com/rss/articles/CBMib2h0dHBzOi8vc3BvcnRvd2VmYWt0eS53cC5wbC90ZW5pcy8xMDUxNTYzL3dza2F6YWxhLXBvd29kLXNsYWJzemVqLWR5c3BvenljamktaWdpLXN3aWF0ZWstbXlzbGUtemUtdG8tbmFzemEtd2luYdIBc2h0dHBzOi8vc3BvcnRvd2VmYWt0eS53cC5wbC9hbXAvdGVuaXMvMTA1MTU2My93c2themFsYS1wb3dvZC1zbGFic3plai1keXNwb3p5Y2ppLWlnaS1zd2lhdGVrLW15c2xlLXplLXRvLW5hc3phLXdpbmE?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:40:49Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "TVP Info",
        title: "Ponad 25 tys. zł kary dla szpitala, w którym pracuje Mama Ginekolog - TVP Info",
        description: null,
        url: "https://news.google.com/rss/articles/CBMijAFodHRwczovL3d3dy50dnAuaW5mby82ODY3ODA3Ni9uZnotcG9uYWQtMjUtdHlzLXpsLWthcnktZGxhLXN6cGl0YWxhLXcta3RvcnltLXByYWN1amUtbWFtYS1naW5la29sb2ctemEtbmllc2x1c3puaWUtcm96bGljem9uYS1ob3NwaXRhbGl6YWNqZdIBAA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:40:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "Do Rzeczy",
        title: "Ukraina. Ostrzał Zaporoża. Uszkodzonych ponad 300 mieszkań - Do Rzeczy",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiXmh0dHBzOi8vZG9yemVjenkucGwvc3dpYXQvNDE5NDc5L3VrcmFpbmEtb3N0cnphbC16YXBvcm96YS11c3prb2R6b255Y2gtcG9uYWQtMzAwLW1pZXN6a2FuLmh0bWzSAVxodHRwczovL2RvcnplY3p5LnBsL2FtcC80MTk0NzkvdWtyYWluYS1vc3RyemFsLXphcG9yb3phLXVzemtvZHpvbnljaC1wb25hZC0zMDAtbWllc3prYW4uaHRtbA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:13:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "BusinessInsider",
        title: "Ile zarabiają policjanci? Za mało. Zwłaszcza w dużych miastach odchodzą na potęgę - BusinessInsider",
        description: null,
        url: "https://news.google.com/rss/articles/CBMigQFodHRwczovL2J1c2luZXNzaW5zaWRlci5jb20ucGwvd2lhZG9tb3NjaS9pbGUtemFyYWJpYWphLXBvbGljamFuY2ktemEtbWFsby16d2xhc3pjemEtdy1kdXp5Y2gtbWlhc3RhY2gtb2RjaG9kemEtbmEtcG90ZWdlL2Zwam1nNnnSAYUBaHR0cHM6Ly9idXNpbmVzc2luc2lkZXIuY29tLnBsL3dpYWRvbW9zY2kvaWxlLXphcmFiaWFqYS1wb2xpY2phbmNpLXphLW1hbG8tendsYXN6Y3phLXctZHV6eWNoLW1pYXN0YWNoLW9kY2hvZHphLW5hLXBvdGVnZS9mcGptZzZ5LmFtcA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T06:01:29Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "BusinessInsider",
        title: "Fed widzi, że banki padają. W efekcie podniesie stopy procentowe jeszcze tylko raz - BusinessInsider",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiggFodHRwczovL2J1c2luZXNzaW5zaWRlci5jb20ucGwvZ29zcG9kYXJrYS9mZWQtd2lkemktemUtYmFua2ktcGFkYWphLXctZWZla2NpZS1wb2RuaWVzaWUtc3RvcHktcHJvY2VudG93ZS1qZXN6Y3plLXR5bGtvLXJhei92cHQ0dHBy0gGGAWh0dHBzOi8vYnVzaW5lc3NpbnNpZGVyLmNvbS5wbC9nb3Nwb2RhcmthL2ZlZC13aWR6aS16ZS1iYW5raS1wYWRhamEtdy1lZmVrY2llLXBvZG5pZXNpZS1zdG9weS1wcm9jZW50b3dlLWplc3pjemUtdHlsa28tcmF6L3ZwdDR0cHIuYW1w?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T05:53:28Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "Gazeta Wyborcza",
        title: "Wielka afera ze sprzętem przeciw COVID-19. Kto w obozie władzy za nią odpowie? - Gazeta Wyborcza",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiZ2h0dHBzOi8vd3lib3JjemEucGwvNyw3NTM5OCwyOTU4NjIwMyx3aWVsa2EtYWZlcmEtemUtc3ByemV0ZW0tcHJ6ZWNpdy1jb3ZpZC0xOS1rdG8tdy1vYm96aWUtd2xhZHp5Lmh0bWzSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T05:00:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "Interia Biznes",
        title: "Google przedstawił Barda. Na razie tylko w USA i Wielkiej Brytanii - Interia Biznes",
        description: null,
        url: "https://news.google.com/rss/articles/CBMicmh0dHBzOi8vYml6bmVzLmludGVyaWEucGwvZ29zcG9kYXJrYS9uZXdzLWdvb2dsZS1wcnplZHN0YXdpbC1iYXJkYS1uYS1yYXppZS10eWxrby13LXVzYS1pLXdpZWxraWVqLWJyeSxuSWQsNjY3MTAxMNIBdWh0dHBzOi8vYml6bmVzLmludGVyaWEucGwvZ29zcG9kYXJrYS9uZXdzYW1wLWdvb2dsZS1wcnplZHN0YXdpbC1iYXJkYS1uYS1yYXppZS10eWxrby13LXVzYS1pLXdpZWxraWVqLWJyeSxuSWQsNjY3MTAxMA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T05:00:00Z",
        content: null,
    },

    {
        source: {
            id: "google-news",
            name: sourceNameBR,
        },
        author: "TVN24",
        title: "Atak Rosji na Ukrainę. Relacja na żywo 23 marca 2023 - TVN24",
        description: null,
        url: "https://news.google.com/rss/articles/CBMiUmh0dHBzOi8vdHZuMjQucGwvc3dpYXQvYXRhay1yb3NqaS1uYS11a3JhaW5lLXJlbGFjamEtbmEtenl3by0yMy1tYXJjYS0yMDIzLTY4NTY3MTDSAQA?oc=5",
        urlToImage: null,
        publishedAt: "2023-03-23T04:35:00Z",
        content: null,
    },
];

export const fakeState = [
    { country: "pl", data: { status: "ok", totalResults: 34, articles: articlesPL } },
    { country: "fr", data: { status: "ok", totalResults: 30, articles: articlesFR } },
    { country: "br", data: { status: "ok", totalResults: 28, articles: articlesBR } },
];

export const fakeStateNoArticles = [{ country: "pl", data: { status: "ok", totalResults: 34 } }];
